name: Upload Data to Google Sheet

on:
  push:
    branches:
      - main

jobs:
  data-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        

      - name: Authenticate with Google
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS_JSON }} #Use the secret name that holds your credentials JSON

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install R packages
        run: |
          Rscript -e 'install.packages("tidyverse")'
          Rscript -e 'install.packages("googlesheets4")'

      - name: readpackages
        run: Rscript -e 'source("req_library.R")'
        
      - name: GA4trafficfunction
        run: Rscript -e 'source("GA4_traffic.R")'
        
      - name: gs_upload
        run: Rscript -e 'source("gs_upload.R")'
              
      
          
          git add .
          git commit -m 'Data updated'
          git push origin main
